In [6]:
import numpy as np
import sympy as sp
import re

In [7]:
plainText = input("Enter the message: ")
key = input("Enter the key: ")

In [8]:
def encrypt(key, text):
  l = [ord(i) - ord('a') for i in re.sub(r'[^\.\!\,a-zA-Z]+', '', text.lower())]
  print("l=", l)
  P = np.array([26 if x == -51 else 27 if x == -53 else 28 if x == -64 else x for x in l] + [23] * ((3 - len(l) % 3) % 3)).reshape(-1, 3).T
  print("P=", P)
  K = np.array([ord(i) - ord('a') for i in key.lower()]).reshape(3, 3)
  print("K=", K)
  print("Cipher=", (K.dot(P) % 29).T)
  return ''.join(['.' if i == 26 else ',' if i == 27 else '!' if i == 28 else chr(i + ord('a')) for i in (K.dot(P) % 29).T.reshape(-1)])

cipher = encrypt(key, plainText)
print(cipher)

l= [5, 6, 1, 3, 18, 1, 18, 3, 5, 1, 18, 3]
P= [[ 5  3 18  1]
 [ 6 18  3 18]
 [ 1  1  5  3]]
K= [[21  3 18]
 [ 5  1 18]
 [ 3  5  1]]
Cipher= [[25 20 17]
 [19 22 13]
 [13  9 16]
 [13 19  9]]
zurtwnnjqntj


In [9]:
K = np.array([ord(i) - ord('a') for i in key.lower()]).reshape(3, 3)
print(np.linalg.inv(K))

[[ 0.06711916 -0.06561086 -0.02714932]
 [-0.03695324  0.02488688  0.21719457]
 [-0.01659125  0.07239819 -0.00452489]]


In [10]:
def decrypt(key, cipher):
  K_inv = np.array(sp.Matrix(np.array([ord(i) - ord('a') for i in key.lower()]).reshape(3, 3)).inv_mod(29))
  print("K_inv=", K_inv)
  l = [ord(i) - ord('a') for i in re.sub(r'[^\.\!\,\#a-zA-Z]+', '', cipher.lower())]
  print("l=", l)
  C = np.array([26 if x == -51 else 27 if x == -53 else 28 if x == -64 else x for x in l]).reshape(-1, 3).T
  print("C=", C)
  print("Decipher=", (K_inv.dot(C) % 31).T)
  return ''.join(['.' if i == 26 else ',' if i == 27 else '!' if i == 28 else chr(i + ord('a')) for i in (K_inv.dot(C) % 29).T.reshape(-1)]).replace('#', '')

print(decrypt("PLMNKOIJB", "AUDGCJVUFZNVJGCMIT"))

K_inv= [[0 12 6]
 [26 13 28]
 [27 19 20]]
l= [0, 20, 3, 6, 2, 9, 21, 20, 5, 25, 13, 21, 9, 6, 2, 12, 8, 19]
C= [[ 0  6 21 25  9 12]
 [20  2 20 13  6  8]
 [ 3  9  5 21  2 19]]
Decipher= [[10 3 6]
 [16 0 8]
 [22 16 24]
 [3 12 9]
 [22 27 25]
 [24 18 19]]
.zfu!djsdvpi.uuhup
